config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'animes#index'
  resources :users, only: [:show]
  resources :animes, only: [:show, :new, :create] do
    collection do
      get 'search'
    end
    resources :reviews, only: [:create, :destroy] do
      resources :comments, only: [:create]
    end
  end

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  post 'watch/:id' => 'watches#create', as: 'create_watch'
  delete 'watch/:id' => 'watches#destroy', as: 'destroy_watch'

  post 'want/:id' => 'wants#create', as: 'create_want'
  delete 'want/:id' => 'wants#destroy', as: 'destroy_want'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :watches, dependent: :destroy
  has_many :watched_users, through: :watches, source: :user
  has_many :wants, dependent: :destroy
  has_many :wanted_users, through: :wants, source: :user

  has_many :reviews

  with_options presence: true do
    validates :image
    validates :name
    validates :furigana
    validates :summary
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates_uniqueness_of :anime_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  has_many :comments, dependent: :destroy

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :likes, dependent: :destroy
  has_many :liked_animes, through: :likes, source: :anime
  has_many :watches, dependent: :destroy
  has_many :watched_animes, through: :watches, source: :anime
  has_many :wants, dependent: :destroy
  has_many :wanted_animes, through: :wants, source: :anime

  has_many :reviews
  has_many :comments

  def already_liked?(anime)
    likes.exists?(anime_id: anime.id)
  end

  def already_watched?(anime)
    watches.exists?(anime_id: anime.id)
  end

  def already_wanted?(anime)
    wants.exists?(anime_id: anime.id)
  end
end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates_uniqueness_of :anime_id, scope: :user_id
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates_uniqueness_of :anime_id, scope: :user_id
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :if_not_admin, only: [:new, :create]

  def index
    @top_like_animes = Anime.find(Like.group(:anime_id).order('count(anime_id) desc').limit(10).pluck(:anime_id))
  end

  def show
    @anime = Anime.find(params[:id])
    @reviews = @anime.reviews
    @review = Review.new
    @comment = Comment.new
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    if @anime.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @animes = SearchAnimesService.search(params[:keyword])
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def anime_params
    params.require(:anime).permit(:name, :furigana, :summary, :image)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_anime

  def create
    Like.create(anime_id: params[:id], user_id: current_user.id)
  end

  def destroy
    @like = Like.find_by(anime_id: params[:id], user_id: current_user.id)
    @like.destroy
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @animes = Anime.all
    @liked_animes = @user.liked_animes
    @watched_animes = @user.watched_animes
    @wanted_animes = @user.wanted_animes
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :set_anime

  def create
    Want.create(anime_id: params[:id], user_id: current_user.id)
  end

  def destroy
    @want = Want.find_by(anime_id: params[:id], user_id: current_user.id)
    @want.destroy
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animeter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Animeterについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'Animeter利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Animeterを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Animeterについて</h2>
      <ul>
        <li><%= link_to 'Animeterガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'Animeterロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to "Animeter", "#", class: "header-logo" %>
  <p>© Animeter</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to "Animeter", "/", class: "header-logo" %>
    <%= form_with url: search_animes_path, local: true, method: :get, class: "search-form" do |f| %>
      <%= f.text_field :keyword, placeholder: 'アニメのタイトルから探す', class: 'input-box' %>
      <%= button_tag type: 'submit', class: 'search-button' do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
    <% if user_signed_in? %>
      <div class='header-list'>
        <%= link_to 'マイページ', user_path(current_user.id), class: "my-page" %>
      </div>
      <div class='header-list'>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
      </div>
    <% else %>
      <div class='header-list'>
        <%= link_to 'ログイン', new_user_session_path, class: "login" %>
      </div>
      <div class='header-list'>
        <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(@anime) %>
    <%= link_to 'お気に入り に登録済み', destroy_like_path(@anime), method: :delete, remote: true, class: "like-button-off" %>
  <% else %>
    <%= link_to 'お気に入り に追加', create_like_path(@anime), method: :post, remote: true, class: "like-button-on" %>
  <% end %>
<% end %>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to "Animeter", "/", class:"second-logo" %>
</header>

app/views/shared/_want.html.erb
<% if user_signed_in? %>
  <% if current_user.already_wanted?(@anime) %>
    <%= link_to '見たい に登録済み', destroy_want_path(@anime), method: :delete, remote: true, class: "want-button-off" %>
  <% else %>
    <%= link_to '見たい に追加', create_want_path(@anime), method: :post, remote: true, class: "want-button-on" %>
  <% end %>
<% end %>

app/views/shared/_watch.html.erb
<% if user_signed_in? %>
  <% if current_user.already_watched?(@anime) %>
    <%= link_to '見た に登録済み', destroy_watch_path(@anime), method: :delete, remote: true, class: "watch-button-off" %>
  <% else %>
    <%= link_to '見た に追加', create_watch_path(@anime), method: :post, remote: true, class: "watch-button-on" %>
  <% end %>
<% end %>