config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'animes#index'
  resources :users, only: [:show]
  resources :animes, only: [:show, :new, :create] do
    collection do
      get 'search'
    end
    resources :reviews, only: [:create, :destroy] do
      resources :comments, only: [:create]
    end
  end

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  post 'watch/:id' => 'watches#create', as: 'create_watch'
  delete 'watch/:id' => 'watches#destroy', as: 'destroy_watch'

  post 'want/:id' => 'wants#create', as: 'create_want'
  delete 'want/:id' => 'wants#destroy', as: 'destroy_want'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :watches, dependent: :destroy
  has_many :watched_users, through: :watches, source: :user
  has_many :wants, dependent: :destroy
  has_many :wanted_users, through: :wants, source: :user

  has_many :reviews

  with_options presence: true do
    validates :image
    validates :name
    validates :furigana
    validates :summary
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates_uniqueness_of :anime_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  has_many :comments, dependent: :destroy

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :likes, dependent: :destroy
  has_many :liked_animes, through: :likes, source: :anime
  has_many :watches, dependent: :destroy
  has_many :watched_animes, through: :watches, source: :anime
  has_many :wants, dependent: :destroy
  has_many :wanted_animes, through: :wants, source: :anime

  has_many :reviews
  has_many :comments

  def already_liked?(anime)
    likes.exists?(anime_id: anime.id)
  end

  def already_watched?(anime)
    watches.exists?(anime_id: anime.id)
  end

  def already_wanted?(anime)
    wants.exists?(anime_id: anime.id)
  end
end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates_uniqueness_of :anime_id, scope: :user_id
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates_uniqueness_of :anime_id, scope: :user_id
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :if_not_admin, only: [:new, :create]

  def index
    @top_like_animes = Anime.find(Like.group(:anime_id).order('count(anime_id) desc').limit(10).pluck(:anime_id))
  end

  def show
    @anime = Anime.find(params[:id])
    @reviews = @anime.reviews
    @review = Review.new
    @comment = Comment.new
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    if @anime.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @animes = SearchAnimesService.search(params[:keyword])
  end

  private

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def anime_params
    params.require(:anime).permit(:name, :furigana, :summary, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to anime_path(@comment.review.anime_id)
  end

  private

  def comment_params
    params.permit(:text, :review_id).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_anime

  def create
    Like.create(anime_id: params[:id], user_id: current_user.id)
  end

  def destroy
    @like = Like.find_by(anime_id: params[:id], user_id: current_user.id)
    @like.destroy
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.create(review_params)
    redirect_to anime_path(@review.anime_id)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to anime_path(params[:anime_id])
  end

  private

  def review_params
    params.require(:review).permit(:text).merge(user_id: current_user.id, anime_id: params[:anime_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @animes = Anime.all
    @liked_animes = @user.liked_animes
    @watched_animes = @user.watched_animes
    @wanted_animes = @user.wanted_animes
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :set_anime

  def create
    Want.create(anime_id: params[:id], user_id: current_user.id)
  end

  def destroy
    @want = Want.find_by(anime_id: params[:id], user_id: current_user.id)
    @want.destroy
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_anime

  def create
    Watch.create(anime_id: params[:id], user_id: current_user.id)
  end

  def destroy
    @watch = Watch.find_by(anime_id: params[:id], user_id: current_user.id)
    @watch.destroy
  end

  private

  def set_anime
    @anime = Anime.find(params[:id])
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/animes/index.html.erb
<%= render "shared/header" %>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to '投稿する', new_anime_path %>
<% end %>
<div class='main'>
  <div class='title-contents'>
    <p class='service-explain'>
      見たアニメを記録して
    </p>
    <p class='service-explain'>
      新しいアニメを見つけよう
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# アニメ一覧 %>
  <div class='item-contents'>
    <h2 class='title'>人気のアニメ</h2>
    <ul class='item-lists'>
      <% @top_like_animes.each_with_index do |anime, i| %>
        <li class='list'>
          <%= link_to anime_path(anime.id) do %>
            <div class='item-img-content'>
              <%= image_tag anime.image.variant(resize: '200x200'), class: "item-img" %>
            </div>
            <span class='reason-list-number'><%= i+1 %></span>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= anime.name %>
              </h3>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /アニメ一覧 %>
</div>
<%= render "shared/footer" %>

app/views/animes/new.html.erb
<%= render "shared/header" %>
<%= form_with model: @anime, url: animes_path, local: true do |f| %>
  <p>画像</p>
  <%= f.file_field :image %>
  <p>名前</p>
  <%= f.text_field :name %>
  <p>ふりがな</p>
  <%= f.text_field :furigana %>
  <p>あらすじ</p>
  <%= f.text_area :summary %>
  <%= f.submit "投稿する" %>
<% end %>

app/views/animes/search.html.erb
<%= render "shared/header" %>
<div class='main'>
  <ul class='item-lists'>
    <% @animes.each do |anime| %>
      <li class='list'>
        <%= link_to anime_path(anime.id) do %>
          <div class='item-img-content'>
            <%= image_tag anime.image.variant(resize: '200x200'), class: "item-img" %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= anime.name %>
            </h3>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<%= render "shared/footer" %>

app/views/animes/show.html.erb
<%= render "shared/header" %>

<div class='anime-details'>
  <div class='anime-detail-left'>
    <h1 class='anime-title'><%= @anime.name %></h1>
    <div class='anime-img-box'>
      <%= image_tag @anime.image.variant(resize: '400x400'), class: "anime-img" %>
    </div>
    <div class='anime-summary'>
      あらすじ
      <p><%= @anime.summary %></p>
    </div>
  </div>
  <div class='anime-detail-right'>
    <div class='anime-buttons'>
      <div class='like-contents', id='like_contents'>
        <%= render 'shared/like' %>
      </div>
      <div class='watch-contents', id='watch_contents'>
        <%= render 'shared/watch' %>
      </div>
      <div class='want-contents', id='want_contents'>
        <%= render 'shared/want' %>
      </div>
    </div>
    <div class='anime-reviews'>
      <% if user_signed_in? %>
        <%= form_with model: [@anime, @review], local: true, class: 'review-form' do |f| %>
          <%= f.text_area :text, placeholder: "レビューを入力", class: 'review-input' %>
          <div class='review-submit-box'>
            <div></div>
            <%= f.submit "投稿する", class: 'review-submit' %>
          </div>
        <% end %>
      <% else %>
        ログインするとレビューを投稿できます
      <% end %>
      <div class='review-contents'>
        <h3>レビュー一覧</h3>
        <% if @reviews.exists? %>
          <% @reviews.each do |review| %>
            <div class='review-content'>
              <div class='review-top'>
                <div class='reviewer-name'>
                  <%= link_to review.user.nickname, user_path(review.user) %> <span><%= review.created_at %></span>
                </div>
                <div class='review-destroy'>
                  <% if user_signed_in? && current_user.id == review.user_id %>
                    <%= link_to '削除する', "/animes/#{review.anime_id}/reviews/#{review.id}", method: :delete %>
                  <% end %>
                </div>
              </div>
              <div class='review-text'>
                <%= review.text %>
              </div>
              <div class='comment-contents'>
                <% if user_signed_in? %>
                  <%= form_with url: "/animes/#{@anime.id}/reviews/#{review.id}/comments", local: true, class: 'comment-form' do |f| %>
                    <%= f.text_area :text, placeholder: "コメントを入力", class: 'comment-input', id: 'comment_text' %>
                    <div class='comment-submit-box'>
                      <%= f.submit "送信", class: 'comment-submit' %>
                    </div>
                  <% end %>
                <% else %>
                  <p>ログインするとこのレビューに対してコメントを送信できます</p>
                <% end %>
                <div id='comments'>
                  <% review.comments.each do |comment| %>
                    <div class='comment-box'>
                      <div class='comment-name'>
                        <%= link_to comment.user.nickname, user_path(comment.user) %> <span><%= review.created_at %></span>
                      </div>
                      <div class='review-text'>
                        <%= comment.text %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          レビューはまだありません
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/likes/create.js.erb
document.getElementById('like_contents').innerHTML = '<%= j(render 'shared/like') %>'

app/views/likes/destroy.js.erb
document.getElementById('like_contents').innerHTML = '<%= j(render 'shared/like') %>'

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='my-page-contents'>
  <h1><%= @user.nickname %>さんのマイページ</h1>
  <div class='my-page-content'>
    <h2 class='my-page-title'>お気に入りのアニメ</h2>
    <div class='item-contents'>
      <ul class='item-lists'>
        <% @liked_animes.each do |anime| %>
          <li class='list'>
            <%= link_to anime_path(anime.id) do %>
              <div class='item-img-content'>
                <%= image_tag anime.image.variant(resize: '200x200'), class: "item-img" %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= anime.name %>
                </h3>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class='my-page-content'>
    <h2 class='my-page-title'>見たアニメ</h2>
    <div class='item-contents'>
      <ul class='item-lists'>
        <% @watched_animes.each do |anime| %>
          <li class='list'>
            <%= link_to anime_path(anime.id) do %>
              <div class='item-img-content'>
                <%= image_tag anime.image.variant(resize: '200x200'), class: "item-img" %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= anime.name %>
                </h3>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class='my-page-content'>
    <h2 class='my-page-title'>見たいアニメ</h2>
    <div class='item-contents'>
      <ul class='item-lists'>
        <% @wanted_animes.each do |anime| %>
          <li class='list'>
            <%= link_to anime_path(anime.id) do %>
              <div class='item-img-content'>
                <%= image_tag anime.image.variant(resize: '200x200'), class: "item-img" %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= anime.name %>
                </h3>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/wants/create.js.erb
document.getElementById('want_contents').innerHTML = '<%= j(render 'shared/want') %>'

app/views/wants/destroy.js.erb
document.getElementById('want_contents').innerHTML = '<%= j(render 'shared/want') %>'

app/views/watches/create.js.erb
document.getElementById('watch_contents').innerHTML = '<%= j(render 'shared/watch') %>'

app/views/watches/destroy.js.erb
document.getElementById('watch_contents').innerHTML = '<%= j(render 'shared/watch') %>'